service: spacecat
frameworkVersion: "3"
useDotenv: true
configValidationMode: error

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - lambda:InvokeFunction
      Resource:
        - arn:aws:dynamodb:us-east-1:*:*
        - arn:aws:lambda:us-east-1:*:*

  environment:
    TENDERLY_PROJECT: project

  httpApi:
      cors: true
      authorizers:
        authorizerFunc:
          type: request
          functionName: authorizerFunc

functions:
  authorizerFunc:
    handler: authorizer.handler
  create-spacecat:
    handler: createSpaceCat.handler
    events:
      - httpApi:
          method: post
          path: /api/create-spacecat
  get-spacecats:
    handler: getSpaceCats.handler
    events:
      - httpApi:
          method: get
          path: /api/get-spacecats